version: '3.9'
services:
  php:
    container_name: ${APP_NAME}_app
    build:
      context: .docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app

  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app:ro
      - logs:/var/log/nginx
    depends_on:
      - php
    ports:
      - "${APP_PORT:-80}:80"

volumes:
  logs:
    name: "${APP_NAME}_logs"
